// import Head from 'next/head'
// import Image from 'next/image'
// import styles from '../styles/Home.module.css'
// import { checkout } from "../checkout"

// export default function Home() {
//   return (
//     <div className={styles.container}>
//       <Head>
//         <title>Tenisky</title>
//         <meta name="description" content="Generated by create next app" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>

//       <main className={styles.main}>
//         <h1 className={styles.title}>
//           Kupte si nejnovější tenisky
//         </h1>

//         <div className={styles.grid}>
//           <div className={styles.card}>
//           <Image 
//             src="/img/tenisky/teniska1.png" 
//             alt="Teniska Jordan 1 Mid GS Fire Red"
//             width={1080}
//             height={673}/>
//             <h2>Jordan 1 Mid GS Fire Red</h2>
//             <p>5.499 Kč</p>
//             <button onClick={(() => {
//                 checkout({
//                   lineItems: [
//                     {
//                       price: "price_1M9umIBMpREfxNmDKPZGpeZq",
//                       quantity: 1
//                     }
//                   ]
//                 })
//               })}>Koupit!</button>
//           </div>

//           <div className={styles.card}>
//             <Image 
//               src="/img/tenisky/teniska2.png" 
//               alt="Teniska Jordan 1 Mid Stealth"
//               width={1080}
//               height={673}/>
//             <h2>Jordan 1 Mid Stealth</h2>
//             <p>4.999 Kč</p>
//               <button onClick={(() => {
//                 checkout({
//                   lineItems: [
//                     {
//                       price: "price_1M9unLBMpREfxNmDg2f9UK0E",
//                       quantity: 1
//                     }
//                   ]
//                 })
//               })}>Koupit!</button>
//           </div>
//         </div>
//       </main>

//       <footer className={styles.footer}>
//         <a
//           href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//           target="_blank"
//           rel="noopener noreferrer"
//         >
//           Powered by{' '}
//           <span className={styles.logo}>
//             <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
//           </span>
//         </a>
//       </footer>
//     </div>
//   )
// }

import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

export default function Home() {
	const handleSubmit = async (event) => {
		event.preventDefault();

		const data = {
			name: event.target.name.value,
			email: event.target.email.value,
		};
    const body = {
      subscriber_data: data,
      resubscribe: false,
      trigger_autoresponders: true
    }
    const JSONbody = JSON.stringify(body)

    const response = await fetch('https://api2.ecomailapp.com/lists/1/subscribe', {
      mode: 'no-cors',  
      method: 'POST',
      headers: {
        'key': process.env.ECOMAIL_API_KEY,
        'Content-Type': 'application/json',
        'Host': 'www.insole.cz'
      },
      body: JSONbody,
    })
    const resdata = await response.json()
    console.log(resdata)
	};

	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.main}>
				<h1 className={styles.title}>
					Welcome to <a href="https://nextjs.org">Next.js!</a>
				</h1>

				<form onSubmit={handleSubmit}>
					<label htmlFor="name">Vaše Jméno</label>
					<input name="name" id="name" type="text"></input>

					<label htmlFor="email">Váš E-Mail</label>
					<input id="email" name="email" type="email"></input>

					<button type="submit">Submit</button>
				</form>
			</main>
		</div>
	);
}
