import Head from "next/head";
import Layout from "../components/layout";
import styles from '../styles/Objednavka.module.css';
import Link from "next/link";

export default function Success() {
   return (
      <>
         <Head>
            <title>Objednávka přijata</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
         </Head>
         <div className={styles.podekovani_area}>
            <Link className={styles.odkazdomu} href="/">Zpět domů</Link>
         </div>
         <h1 className={styles.podekovani}>Děkujeme za objednávku</h1>
      </>
   )
}