import Head from "next/head"

export default function Success() {
   return (
      <>
         <Head>
            <title>Objednávka přijata</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
         </Head>
         <h1>Děkujeme za objednávku</h1>
      </>
   )
}